async originalPage => {
  const browser = originalPage.context().browser();
  const context = await browser.newContext({viewport:{width:390,height:844}});
  const page = await context.newPage();
  const ready = () => page.waitForFunction(()=>document.querySelector('#app')?.getAttribute('aria-busy')==='false');
  const check = (ok,msg) => {if(!ok) throw new Error(msg);};
  const command = async text => {await page.locator('#terminal-input').fill(text); await page.locator('#terminal-input').press('Enter'); await ready();};
  const dir='/Users/iron/orca/projects/gitlearn/src/ui/evidence/onboarding';
  await page.goto('http://127.0.0.1:4177/'); await ready();
  const inputBox=await page.locator('#terminal-input').boundingBox();
  check(inputBox.y+inputBox.height<=844,'landing input below fold at 390px');
  await page.screenshot({path:dir+'/S1-390-light.png',fullPage:true});
  await page.locator('#theme-toggle').click(); await page.screenshot({path:dir+'/S1-390-dark.png',fullPage:true});
  await page.locator('#start-button').click(); await ready();
  check((await page.locator('#terminal-output').innerText()).includes('❯ git status'),'CTA executes same terminal');
  await page.locator('#check-button').click(); await ready();
  await page.waitForTimeout(21000);
  check((await page.locator('#hints').innerText()).includes('힌트 1'),'20 seconds idle automatically reveals hint');
  await page.locator('#hint-button').click(); await page.getByRole('button',{name:'정답 보기',exact:true}).click();
  check(await page.getByRole('button',{name:'이 단계만 대신 하기',exact:true}).count()===0,'assist not immediately exposed');
  await command('git nope');
  await page.getByRole('button',{name:'이 단계만 대신 하기',exact:true}).click(); await ready();
  check((await page.locator('#step-heading').innerText()).includes('03'),'assist executes and advances');
  check((await page.locator('#staged-list').innerText()).includes('validator.test.ts'),'assist creates index state');
  check(!(await page.locator('#staged-list').innerText()).includes('.env.local'),'assist leaves personal file outside index');
  await page.locator('#check-button').click(); await ready();
  await command('git commit -m "fix: wrong message"');
  await page.locator('#hint-button').click(); await page.locator('#hint-button').click();
  await page.getByRole('button',{name:'정답 보기',exact:true}).click();
  await command('git nope'); await page.getByRole('button',{name:'이 단계만 대신 하기',exact:true}).click(); await ready();
  check((await page.locator('#step-heading').innerText()).includes('05'),'assist repairs wrong commit from baseline');
  await page.locator('#check-button').click(); await ready();
  await page.locator('#file-path').fill('.gitignore'); await page.getByRole('button',{name:'열기',exact:true}).click();
  await page.locator('#edit-content').fill((await page.locator('#edit-content').inputValue())+'\n.cache/\n');
  await page.getByRole('button',{name:'저장',exact:true}).click(); await ready();
  await page.locator('#hint-button').click(); await page.locator('#hint-button').click();
  await page.getByRole('button',{name:'정답 보기',exact:true}).click(); await command('git nope');
  await page.getByRole('button',{name:'이 단계만 대신 하기',exact:true}).click(); await ready();
  check(await page.locator('#app').getAttribute('data-screen')==='complete','assisted final ignore commit completes');
  check((await page.locator('#terminal-output').textContent()).includes('.cache/'),'assist preserves existing ignore rules');
  check((await page.locator('#completion-screen').innerText()).includes('6단계 (대신 실행)'),'completion records assisted steps');
  await page.screenshot({path:dir+'/S4-assisted-390-dark.png',fullPage:true});
  await page.getByRole('button',{name:'계정 만들고 진도 저장하기',exact:true}).click();
  await page.locator('#account-email').fill('learner@example.invalid');
  await page.getByRole('button',{name:'연결 상태 확인',exact:true}).click();
  check((await page.locator('#account-status').innerText()).includes('생성·로그인하지 못했습니다'),'account UI does not claim account created');
  await page.getByRole('button',{name:'학습으로 돌아가기',exact:true}).click();
  await page.locator('#catalog-button').click();
  await page.getByRole('button',{name:'06 · 리뷰 요청대로 커밋 쪼개기',exact:true}).click(); await ready();
  await page.waitForTimeout(21000);
  check(!(await page.locator('#hints').innerText()).includes('힌트 1'),'intermediate does not auto hint on idle');
  await command('git nope'); check((await page.locator('#hints').innerText()).includes('힌트 1'),'intermediate hint after error');
  check(await page.getByRole('button',{name:'정답 보기',exact:true}).count()===0,'intermediate has no answer');
  await page.locator('#catalog-button').click();
  await page.getByRole('button',{name:'40 · 사라진 커밋 되찾기',exact:true}).click(); await ready();
  await command('git nope'); check(!(await page.locator('#hints').innerText()).includes('힌트 1'),'advanced no automatic hint after error');
  await page.locator('#hint-button').click(); check((await page.locator('#hints').innerText()).includes('힌트 1'),'advanced manual hint');
  check(await page.getByRole('button',{name:'정답 보기',exact:true}).count()===0,'advanced no answer');
  await context.close();
  const denied = await browser.newContext();
  await denied.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Blocked','SecurityError');}});});
  const deniedPage=await denied.newPage(); await deniedPage.goto('http://127.0.0.1:4177/');
  await deniedPage.locator('#start-button').click();
  await deniedPage.waitForFunction(()=>document.querySelector('#app')?.getAttribute('aria-busy')==='false');
  check(await deniedPage.locator('#app').getAttribute('data-screen')==='workbench','localStorage failure keeps practice working');
  check((await deniedPage.locator('.page-footer').innerText()).includes('진도를 저장할 수 없습니다'),'storage failure shown truthfully');
  await denied.close();
  return {mobileLandingAboveFold:true,ctaContinuity:true,idleHint:true,assistedStages:[2,4,6],intermediatePolicy:true,advancedPolicy:true,accountHonest:true,storageDeniedUsable:true};
}
